platform :ios, 8.0
target 'AdtradeSDK' do
	pod 'Adtrade', :path => '../'
	pod 'AdtradeAPI', :path => 'Development Pods/AdtradeAPI'	
	pod 'ATNetworking', :path => 'Development Pods/ATNetworking'	
	
end

target 'AdtradeSDKTests' do
#	pod 'Adtrade', :path => '../'
#	pod 'AdtradeAPI', :git => 'https://github.com/adtrade/AdtradeAPI.git'
#	pod 'ATNetworking', :git => 'https://github.com/adtrade/ATNetworking.git'
end


